import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f0f2f5',
  },
  emptyContainer: {
    flex: 1,
    backgroundColor: 'white',
  },
  modalViewStyle: {
    backgroundColor: 'rgba(0,0,0,0.7)',
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
    flexDirection: 'column',
  },
  movieInfoView: {
    backgroundColor: 'white',
    borderRadius: 14,
    width: 340,
  },
  header: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#292524',
    alignSelf: 'center',
    paddingTop: 7,
  },
  label: {
    fontSize: 15,
    color: '#749cd3',
    marginStart: 15,
    fontWeight: 'bold',
  },
  input: {
    height: 35,
    margin: 5,
    borderWidth: 1,
    padding: 10,
    borderRadius: 5,
    marginStart: 15,
  },

  overviewInput: {
    height: 50,
    margin: 5,
    borderWidth: 1,
    padding: 10,
    borderRadius: 5,
    marginStart: 15,
  },

  datePickerView: {
    padding: 5,
    marginStart: 15,
    margin: 5,
    borderRadius: 5,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  calendarIcon: {
    justifyContent: 'center',
    marginStart: 5,
    alignSelf: 'center',
    color: '#749cd3',
    paddingRight: 8,
    fontSize: 30,
  },
  posterButtonsView: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 10,
  },
  posterButton: {
    backgroundColor: '#f0f2f5',
    borderRadius: 10,
    width: 130,
    height: 55,
    justifyContent: 'center',
    marginStart: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  photoLibraryIcon: {
    color: '#749cd3',
    paddingRight: 8,
    fontSize: 30,
  },
  posterText: {
    fontWeight: 'bold',
    color: 'black',
    alignSelf: 'center',
    fontSize: 16,
  },
  cameraIcon: {
    color: '#749cd3',
    paddingRight: 8,
    fontSize: 28,
  },
  moviePosterView: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 7,
    marginBottom: 7,
  },
  poster: {
    width: 230,
    height: 230,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.8,
    shadowRadius: 7,
  },
  buttonsView: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: '#C4C4C4',
    height: 60,
  },
  firstButton: {
    borderRightWidth: 1,
    borderRightColor: '#C4C4C4',
    flex: 1,
    justifyContent: 'center',
  },
  buttonText: {
    textAlign: 'center',
    fontSize: 17,
    fontWeight: 'bold',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondButton: {
    flex: 1,
    justifyContent: 'center',
  },
  noMoviesView: {
    marginTop: 70,
    alignContent: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#292524',
    marginTop: 20,
    marginBottom: 20,
  },
  info: {
    fontSize: 15,
    fontStyle: 'italic',
    color: '#292524',
  },
  createMovieIcon: {
    color: '#749cd3',
    paddingRight: 8,
    fontSize: 35,
  },
  addMovieButton: {
    margin: 20,
    backgroundColor: '#f0f2f5',
    borderRadius: 15,
    width: 190,
    height: 55,
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
  },
  addMovieIcon: {
    color: '#749cd3',
    fontSize: 45,
  },
  addMovieText: {
    fontWeight: 'bold',
    color: 'black',
    alignSelf: 'center',
    fontSize: 17,
  },
  icon: {
    width: 50,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    top: 10,
    right: 10,
    position: 'absolute',
    borderRadius: 100,
  },
  // AndroidSafeArea: {
  //   paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
  // },
});
